### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by gamm08** [Alottachairs/WFH-Late-Shift#1]
How do you like the idea of ​​doing something like backrooms?

**Comment by Alottachairs** [comment]
Yeah I like that creepy vibe of those liminol spaces

**Comment by gamm08** [comment]
can you give me your contacts?  i want to write to you

**Comment by Alottachairs** [comment]
Sure! You can find me on Discord Nooch#6555

I'm sure you can guess by looking at my code and still a beginner. I'm down to collaborate but mostly this project is my first 3d game and will be the largest thing i've done so far. 

Currently i'm learning blender right now to make better scenes and textures and the like
